services:
  pgdb:
    image: postgres:17
    environment:
      POSTGRES_DB: employment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-15T19-57-03Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbucket:
    image: minio/mc:latest
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 minio minio123;
      /usr/bin/mc mb s3/images;
      /usr/bin/mc anonymous set public s3/images;
      "

  django:
    build: .

    depends_on:
      - pgdb
      - minio
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000  # Добавьте эту строку, если ее нет

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9002:9000"  # Измените этот порт
      - "9003:9001"  # Измените и этот порт
    depends_on:
      - minio

  redis:
    depends_on:
      - pgdb
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

volumes:
  pgdata:
  minio-data: